const bcrypt = require('bcryptjs');

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  await knex('users').del()
  await knex('users').insert([
    {
      // id: 1,
      first_name: 'Сардор',
      last_name: 'Юлдашев',
      gender: "male",
      username: 'sardor',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 2,
      first_name: 'Константин',
      last_name: 'Пожалов',
      gender: "male",
      username: 'konstantin',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 3,
      first_name: 'Владимир',
      last_name: 'Торсуев',
      gender: "male",
      username: 'vladimir',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 4,
      first_name: 'Артемий',
      last_name: 'Пресняков',
      gender: "male",
      username: 'artik',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 5,
      first_name: 'Эдуард',
      last_name: 'Асадов',
      gender: "male",
      username: 'eduard',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 6,
      first_name: 'Виктор',
      last_name: 'Астафьев',
      gender: "male",
      username: 'viktor',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 7,
      first_name: 'Елена',
      last_name: 'Райтман',
      gender: "female",
      username: 'yelena',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 8,
      first_name: 'Сергей',
      last_name: 'Жарков',
      gender: "male",
      username: 'sergey',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 9,
      first_name: 'Кристина',
      last_name: 'Агилера',
      gender: "female",
      username: 'kristina',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 10,
      first_name: 'Анатолий',
      last_name: 'Карпов',
      gender: "male",
      username: 'anatoliy',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 11,
      first_name: 'Леонид',
      last_name: 'Быков',
      gender: "male",
      username: 'leonid',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 12,
      first_name: 'Филипп',
      last_name: 'Янковский',
      gender: "male",
      username: 'filipp',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 13,
      first_name: 'Лариса',
      last_name: 'Конюшкова',
      gender: "female",
      username: 'larisa',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 14,
      first_name: 'Андрей',
      last_name: 'Козлов',
      gender: "male",
      username: 'andrey',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 15,
      first_name: 'Владислав',
      last_name: 'Радимов',
      gender: "male",
      username: 'whatislove',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 16,
      first_name: 'Аяна',
      last_name: 'Касымова',
      gender: "female",
      username: 'ayana',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 17,
      first_name: 'Александр',
      last_name: 'Серов',
      gender: "male",
      username: 'alexandro',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 18,
      first_name: 'Василий',
      last_name: 'Ливанов',
      gender: "male",
      username: 'vasiliy',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 19,
      first_name: 'Ольга',
      last_name: 'Кормухина',
      gender: "female",
      username: 'olga',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 20,
      first_name: 'Олег',
      last_name: 'Шепс',
      gender: "male",
      username: 'oleg',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 21,
      first_name: 'Алексей',
      last_name: 'Макаров',
      gender: "male",
      username: 'aleksey',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 22,
      first_name: 'Любовь',
      last_name: 'Орлова',
      gender: "female",
      username: 'love_or_eagle',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 23,
      first_name: 'Серафим',
      last_name: 'Сашлиев',
      gender: "male",
      username: 'serafim',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 24,
      first_name: 'Анастасия',
      last_name: 'Решетова',
      gender: "female",
      username: 'anastasia',
      password: bcrypt.hashSync('1234', 10),
    },
    {
      // id: 25,
      first_name: 'Геннадий',
      last_name: 'Хазанов',
      gender: "male",
      username: 'gena',
      password: bcrypt.hashSync('1234', 10),
    },
  ]);
};